os: linux
dist: bionic
language: c++

before_install:
        - export DEBIAN_FRONTEND=noninteractive

install:
        - sudo apt-get update
        - sudo apt-get install git build-essential srecord unzip wget tree python3-pip python3-setuptools python3-wheel clang bison flex libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev
        - pip3 install wheel
        - pip3 install -r $(pwd)/ibex/python-requirements.txt

        - wget https://raw.githubusercontent.com/lowRISC/opentitan/master/util/get-toolchain.py # Lowrisc RISCV toolchain
        - python3 get-toolchain.py -t /home/travis/tools/riscv
        - export PATH="$PATH:/home/travis/tools/riscv/bin"
        - cd ibex && git apply ../ibex.patch && make sw-led && fusesoc --cores-root=. run --target=synth --setup lowrisc:ibex:top_artya7 --part xc7a35ticsg324-1L && cd ..
script:
        - cd yosys && sudo make install -j$(nproc) && cd ..
        - export ROOT_DIR=${PWD}
        - export IBEX_BUILD_DIR="${ROOT_DIR}/ibex/build"

        - python3 yosys.py
