os: linux
dist: bionic
language: c++

before_install:
        - export DEBIAN_FRONTEND=noninteractive

install:
        - sudo apt-get update
        - sudo apt-get install git build-essential srecord unzip wget tree python3-pip python3-setuptools python3-wheel clang bison flex libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev

        - wget https://raw.githubusercontent.com/lowRISC/opentitan/master/util/get-toolchain.py
        - python3 get-toolchain.py --install-dir ${PWD}/riscv/
        - export PATH="$PATH:${PWD}/riscv/bin:${PWD}/env/symbiflow/bin"
script:
        - export ROOT_DIR=${PWD}
        - export IBEX_BUILD_DIR="${ROOT_DIR}/ibex/build"

        - make env

        - cd yosys && make install -j$(nproc) PREFIX=${ROOT_DIR}/env/conda/envs/xc7 && cd ..

        - make yosys/plugins
        - make ibex/configure
        - make all
