name: xc7
channels:
  - symbiflow
dependencies:
  - symbiflow::symbiflow-vtr=8.0.0.rc2_5415_gd6d69ff92=20201120_180018
  - symbiflow::prjxray-db
  - symbiflow::prjxray-tools
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  - gxx_linux-64
  # Packages installed from PyPI
  - pip:
    - -r file:requirements.txt
