name: xc7
channels:
  - symbiflow
dependencies:
  - symbiflow::symbiflow-yosys-plugins=1.0.0.7_0174_g5e6370a=20201012_171341
  - symbiflow::symbiflow-vtr=8.0.0.rc2_5415_gd6d69ff92=20201120_180018
  - symbiflow::prjxray-db=0.0_0230_g485a837
  - symbiflow::prjxray-tools
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  - gxx_linux-64
  # Packages installed from PyPI
  - pip:
    - -r file:requirements.txt
