name: CI tests

on: [push, pull_request]

jobs:

  Run-tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install git build-essential srecord unzip wget tree python3-pip python3-setuptools python3-wheel clang bison flex libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev make

    - name: Download & install lowRISC toolchain
      run: |
        make toolchain

    - name: Download conda environment
      run: |
        make env

    - name: Build & install yosys
      run: |
        make yosys/build
        make yosys/plugins

    - name: Export PATH
      run: |
        echo "${PWD}/riscv/bin" >> ${GITHUB_PATH}
        echo "${PWD}/env/symbiflow/bin" >> ${GITHUB_PATH}

    - name: Configure Ibex
      run: make ibex/configure

    - name: Generate bitstream
      run: make all

    - uses: actions/upload-artifact@v2
      with:
        name: top_artya7.bit
        path: build/top_artya7.bit
